print("Hello world!")
print("Hello Git")
print("Hello Commit 1")
print("Hello Commit 2")
print("gute nacht")
print("03/09/2023")
print("06/09/2023")
print("proverka")
print("proverka1")
print("proverka2")
print("proverka3")
print("proverka3")
print("proverka3")
print("proverka3")
